-
  name: Deploy a web application
  hosts: db_and_web_server3, db_and_web_server4
  tasks:
    - name: Install dependencies
      apt: name={{ item }} state=present
      with_items:
       - python
       - python-setuptools
       - python-dev
       - build-essential
       - python-pip
       - python-mysqldb
    - include: tasks/deploy_db.yml
    - include: tasks/deploy_web.yml
